config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'posts/new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @posts = Post.all.order("created_at desc")

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EzBlog</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Rubik" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- fb stuff -->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = 'https://connect.facebook.net/pt_PT/sdk.js#xfbml=1&version=v3.2&appId=345613179594716&autoLogAppEvents=1';
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <!-- /fb stuff -->
    <!-- navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/">
        ez <i class="fab fa-blogger-b"></i>
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menu" aria-controls="menu" aria-expanded="false" aria-label="Toggle menu">
        <i class="fas fa-ellipsis-h"></i>
      </button>

      <div class="collapse navbar-collapse" id="menu">
        <ul class="navbar-nav m-auto">
          <li class="nav-item active">
            <a href="/" class="nav-link" data-no-turbolink="true"><i class="fas fa-home"></i> HOME</a>
          </li>
          <li class="nav-item">
            <a href="<%= posts_new_path %>" class="nav-link" data-no-turbolink="true"><i class="far fa-plus-square"></i> POST</a>
          </li>
        </ul>
      </div>
    </nav>
    <!-- /navigation -->
    <div id="main_body" class="container-fluid px-0 px-md-2">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_post_get.html.erb
<% @posts.each do |post| %>
  <div class="col-12 border rounded bg-light shadow-sm mb-2 post_wrapper">

    <!-- post header -->
    <div class="row border-bottom">

      <!-- title -->
      <div class="col-12 post_head">
        <a href="<%= posts_path %>/<%= post.id %>"><%= post.title %></a>
      </div>
      <!-- meta -->
      <div class="col-12 post_meta">
        <%= post.updated_at %>
      </div>

    </div>
    <!-- /post header -->

    <!-- post body -->
    <div class="row">

      <!-- message -->
      <div class="col-12 post_content text-justify border-bottom">
        <%= post.message %>
      </div>
      <!-- /message -->

      <!-- read more -->
      <div class="col-12 post_action text-right py-2">
        <%= link_to "read all", post, class: "btn btn-outline-secondary btn-sm", :"data-turbolinks" => false %>
      </div>
      <!-- /read more -->

    </div>
    <!-- /post body -->

  </div>
<% end %>

app/views/pages/index.html.erb
<!-- section wrapper -->
<div id="section_wrapper_index" class="px-0 mx-0">

  <!-- title -->
  <div class="row header">
    <div class="col-6">
      <h1>::posts>_</h1>
    </div>

    <div class="col-6 text-right">
      <span id="live_clock"></span>
    </div>
  </div>
  <!-- /title -->

  <!-- content >> grid x 2 -->
  <div class="row post_content">

    <!-- left grid -->
    <div class="col-12 col-md-8 m-0 px-0 px-md-3">
      <div class="row wrapper_post">
        <%= render @posts %>
      </div>
    </div>
    <!-- /left grid -->

    <!-- right grid -->
    <div class="d-none d-md-block col-md-4">
      <div class="row wrapper_sidebar">
        <div class="col-12 border rounded bg-light shadow-sm text-justify">
          This is the sidebar.<br>
          Useful but unnecessary information will be displayed here.<br>
          Tags and user count, latest posts, etc.<br>
          <br>
          Only visible above MD.
        </div>
      </div>
    </div>
    <!-- /right grid -->

  </div>
  <!-- /content -->

</div>
<!-- /end of section wrapper -->

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class:"w-100" %>
    <%= form.text_field :title, class: "w-100" %>
  </div>

  <div class="field">
    <%= form.label :message, class: "w-100" %>
    <%= form.text_area :message, class: "w-100", size: "100x10" %>
  </div>

  <div class="actions row">

    <div class="col-6 text-center">
      <%= form.submit "Create Post", class: "btn btn-success w-50" %>
    </div>

    <div class="col-6 text-center">
      <a href="<%= root_path %>" class="btn btn-warning w-50">Go Back</a>
    </div>

  </div>
<% end %>

app/views/posts/_post.html.erb
  <div class="col-12 border rounded bg-light shadow-sm mb-2 post_wrapper">

    <!-- post header -->
    <div class="row border-bottom">

      <!-- title -->
      <div class="col-12 post_head">
        <a href="<%= posts_path %>/<%= post.id %>"><%= post.title %></a>
      </div>
      <!-- meta -->
      <div class="col-12 post_meta">
        <%= post.updated_at %>
      </div>

    </div>
    <!-- /post header -->

    <!-- post body -->
    <div class="row">

      <!-- message -->
      <div class="col-12 post_content text-justify border-bottom">
        <%= truncate(post.message, length: 400, separator: " ", omission:" ...") %>
      </div>
      <!-- /message -->

      <!-- read more -->
      <div class="col-12 post_action text-right py-2">
        <%= link_to "read all", post, class: "btn btn-outline-secondary btn-sm float-right", :"data-turbolinks" => false %>
      </div>
      <!-- /read more -->

    </div>
    <!-- /post body -->

  </div>

app/views/posts/edit.html.erb
<!-- section wrapper -->
<div id="section_wrapper_editpost" class="px-0 mx-0">
  <!-- title -->
  <div class="row header">
    <div class="col-6">
      <h1>::posts/edit>_</h1>
    </div>

    <div class="col-6 text-right">
      <span id="live_clock"></span>
    </div>
  </div>
  <!-- /title -->

  <!-- form -->
  <div class="row form_wrapper">
    <div class="col-12">
      <%= render 'form', post: @post %>
    </div>
  </div>
  <!-- /form -->

  <div class="actions row">

    <div class="col-12 text-center mt-5">
      <%= link_to 'Show Post', @post, class: "btn btn-outline-primary w-10" %>
    </div>

  </div>
</div>
<!-- /section wrapper -->

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.message %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<!-- section wrapper -->
<div id="section_wrapper_newpost" class="px-0 mx-0">

  <!-- title -->
  <div class="row header">
    <div class="col-6">
      <h1>::posts/new>_</h1>
    </div>

    <div class="col-6 text-right">
      <span id="live_clock"></span>
    </div>
  </div>
  <!-- /title -->

  <!-- form -->
  <div class="row form_wrapper">
    <div class="col-12">
      <%= render 'form', post: @post %>
    </div>
  </div>
  <!-- /form -->

</div>
<!-- /section wrapper -->

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<!-- section wrapper -->
<div id="section_wrapper_post" class="px-0 mx-0">
<p id="notice"><%= notice %></p>
  <!-- title -->
  <div class="row header">
    <div class="col-6">
      <h1>::posts/read> <%= @post.title %>.</h1>
    </div>

    <div class="col-6 text-right">
      <span id="live_clock"></span>
    </div>
  </div>
  <!-- /title -->

  <!-- post -->
  <div class="row post_wrapper justify-content-center">

    <div class="col-12 col-md-8 border rounded bg-light">

      <div class="col-12 p-0">
        <h3 class="mt-2"><%= @post.title %></h3>
        <p class="text-justify"><%= @post.message %></p>
      </div>

      <div class="col-12 p-0 border-top post_meta">

        <div class="row py-2 border-bottom">
          <div class="col-6 text-left p-0 align-self-center">
            <div class="col-6 px-0">
              <%= link_to "back", root_path, class: "btn btn-outline-secondary btn-sm" %>
              <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-outline-warning btn-sm" %>
            </div>
          </div>

          <div class="col-6 text-right p-0 align-self-center">
            <%= @post.updated_at %>
          </div>
        </div>

        <div class="row">
          <div class="col-12 p-0 pt-2">
            <div class="fb-comments" data-href="http://<%= request.host+request.fullpath %>" data-width="100%" data-numposts="5"></div>
          </div>
        </div>



      </div>

    </div>

  </div>
  <!-- /post -->

</div>
<!-- /section wrapper -->